---
- name: Create read-only user
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ pg_ro_user }}"
    password: "{{ pg_ro_password }}"

- name: revoke create table permissions from public
  become: true
  become_user: postgres
  command: "psql --no-psqlrc --no-align --tuples-only --quiet --echo-queries --command='REVOKE ALL ON SCHEMA public FROM public; GRANT USAGE ON SCHEMA public TO public; GRANT ALL ON SCHEMA public TO \"{{ pg_users[0].name }}\";' \"{{ pg_ro_database }}\""

- name: prepare SQL
  template:
    src: create-ro-user.sql.j2
    dest: /tmp/create-ro-user.sql
    owner: "{{ pg_admin_user }}"
    group: "{{ pg_admin_user }}"
    mode: 0600

- name: execute SQL
  command: "psql -U \"{{ pg_users[0].name }}\" --no-psqlrc --no-align --tuples-only --quiet --echo-queries --file=\"/tmp/create-ro-user.sql\" \"{{ pg_ro_database }}\""
  environment:
    PGPASSWORD: "{{ pg_users[0].password }}"

- name: cleanup
  file:
    path: /tmp/create-ro-user.sql
    state: absent
